### ISSUE TITLE
TestStruct_DoubleBus_Ring & TestStruct_DoubleBus_Ring2 malfunction

### ISSUE THREAD

**Issue by oscar-ubc** [SiEPIC/SiEPIC_EBeam_PDK#192]
When add instance TestStruct_DoubleBus_Ring from the library EBeam-dev [Technology EBeam],  an error message:  Unknown lib 'SiEPIC-EBeam PCells' in PcellDeclaration.produce 

When add instance  TestStruct_DoubleBus_Ring2  from the library EBeam-dev [Technology EBeam], an error message: 'NoneType' Object has no attribute 'cell_index' in PCellDeclaration.produce

**Comment by StephenHLin** [comment]
Hi Oscar,
I just tested this, the error is because we renamed SiEPIC-EBeam PDK to EBeam-Dev recently and forgot about this component's import name.

It's a relative easy fix around line 1457 for SiEPIC_Ebeam_dev Library:
change `lib = Library.library_by_name("SiEPIC-EBeam PDK")`
to `lib = Library.library_by_name("EBeam-dev")`
and it should work.

You can do the same thing for TestStruct_DoubleBus_Ring2.
I'll put in a commit in a bit that will include this.

**Comment by oscar-ubc** [comment]
Thanks Stephen! I will try it tomorrow.Regards,OscarSent from my Huawei Mobile-------- Original Message --------Subject: Re: [lukasc-ubc/SiEPIC_EBeam_PDK] TestStruct_DoubleBus_Ring & TestStruct_DoubleBus_Ring2 malfunction (#192)From: Stephen To: lukasc-ubc/SiEPIC_EBeam_PDK CC: oscar-ubc ,Author Hi Oscar,
I just tested this, the error is because we renamed SiEPIC-EBeam PDK to EBeam-Dev recently and forgot about this component's import name.
It's a relative easy fix around line 1457 for SiEPIC_Ebeam_dev Library:
change lib = Library.library_by_name("SiEPIC-EBeam PDK")
to lib = Library.library_by_name("EBeam-dev")
and it should work.
You can do the same thing for TestStruct_DoubleBus_Ring2.
I'll put in a commit in a bit that will include this.
